version: '3'
services:
  react-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /app
    ports: 
      - "3000:3000"
    volumes:
      - ./app/src/:/app/src/
      - ./app/public/:/app/public/
